---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3024146906-6CnOaHqgbEnggSE5cLqXbEUGnLeQK8bBnsxAcXA
:access_token_secret: 72c4GOIWmB8CUcknR5zJTzyEamqOyQiXpVA0dJaAHG06l
